### ISSUE TITLE
GL_MAX_VARYING_FLOATS is 0 on MacOS

### ISSUE THREAD

**Issue by Gnimuc** [capnramses/antons_opengl_tutorials_book#12]
i'm working on EI Capitan. after running `01_extended_init` example, i find the `GL_MAX_VARYING_FLOATS` is `0`, which seems an unexpected result.

```
GL_LOG_FILE log. local time Fri Oct  9 17:06:29 2015
build version: Oct  2 2015 19:54:21

starting GLFW
3.0.2 Cocoa NSGL chdir menubar
renderer: Intel HD Graphics 4000 OpenGL Engine
version: 4.1 INTEL-10.8.77
GL Context Params:
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS 80
GL_MAX_CUBE_MAP_TEXTURE_SIZE 16384
GL_MAX_DRAW_BUFFERS 8
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS 4096
GL_MAX_TEXTURE_IMAGE_UNITS 16
GL_MAX_TEXTURE_SIZE 16384
GL_MAX_VARYING_FLOATS 0
GL_MAX_VERTEX_ATTRIBS 16
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS 16
GL_MAX_VERTEX_UNIFORM_COMPONENTS 4096
GL_MAX_VIEWPORT_DIMS 16384 16384
GL_STEREO 0
-----------------------------
 ```

>GL_MAX_VARYING_FLOATS
data returns one value, the maximum number of interpolators available for processing varying variables used by vertex and fragment shaders. This value represents the number of individual floating-point values that can be interpolated; varying variables declared as vectors, matrices, and arrays will all consume multiple interpolators. The value must be at least 32.

the doc says this value should be at least 32 and the output of my julia code is
`GL_MAX_VARYING_FLOATS: 16384`.  any idea?

**Comment by capnramses** [comment]
i'm not sure! perhaps it's something that's changed in the specification. i'll give it a try on my mini.

**Comment by capnramses** [comment]
GL_MAX_VARYING_FLOATS 0 on my mini also. it's going to take some digging through the specification documents to find out about that. guess 1: it's from an older specification which apple doesn't support in e.g. 4.1 core and there's some other macro to check. guess 2: it's a bug / left out in the apple impl.

**Comment by Gnimuc** [comment]
yes, i should blame apple, and also myself. there was a bug in my julia code, so if the value of `GL_MAX_VARYING_FLOATS` is always equal to the value of `GL_MAX_TEXTURE_SIZE`. i've fixed that bug and now two codes give the same result which is reasonable for me. 

many thanks :+1:  have a nice day!
