### ISSUE TITLE
Binding the same vertex buffer object (vbo) twice?

### ISSUE THREAD

**Issue by mschwan** [capnramses/antons_opengl_tutorials_book#13]
In the [00_hello_triangle](https://github.com/capnramses/antons_opengl_tutorials_book/blob/master/00_hello_triangle/main.c) project the vertex buffer object `vbo` is being bound twice, the first time in [line 97](https://github.com/capnramses/antons_opengl_tutorials_book/blob/master/00_hello_triangle/main.c#L97) (which is what one would expect) and then again in [line 108](https://github.com/capnramses/antons_opengl_tutorials_book/blob/master/00_hello_triangle/main.c#L108). This seems to be unnecessary or am I missing something? At least the program runs fine only binding it once.

**Comment by capnramses** [comment]
you are correct, that is a redundant call! i left these in deliberately.
IME it's a bigger and more common problem when students are copy-pasting fragments into functions and lose track of state, or rather which states need to be bound for which functions, so i generally leave these redundant calls in to make it more obvious. could this be done in a tidier way...probably, but i don't want to introduce my own encapsulation style ideas etc. suggestions welcome.

**Comment by capnramses** [comment]
added a comment explaining this in 00_hello_triangle
