### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Fwjrei** [capnramses/antons_opengl_tutorials_book#14]
https://github.com/capnramses/antons_opengl_tutorials_book/blob/master/25_sprite_sheets/main.cpp
Line 85, asserting on P_loc a second time. A static analyzer would probably catch this.
Line 217, comment typo.

**Comment by capnramses** [comment]
thanks Fwjrei! Fixed that one. I'm sure there are plenty more of them in there.

**Comment by Fwjrei** [comment]
Sure, in that same file, in main(), glDrawArrays happens on line 268 but glUniformMatrix4fv (V_loc, 1, GL_FALSE, V.m) happens on line 357. In effect, the position updating is late, since the triangles are rendered before the matrix is updated. The fix is to move glDrawArrays down to just above the buffer swap.

**Comment by capnramses** [comment]
thanks again! i think that one is okay ... i set a default value in create_shaders() i think, so it shouldn't produce a flicker at start-up. i don't usually mind if animation updates chase behind by 1 frame, i don't think it should be noticeable, but it would also be fine to do all animation updates before all the drawing. feel free to do pull requests for typos etc and i'll absorb them in! i'm buried in game development at the moment so i haven't had time for a thorough look through this code-base for a while.
