### ISSUE TITLE
On linux, with `radeon` driver, the same glfwWindowHint workaround is required.

### ISSUE THREAD

**Issue by guysherman** [capnramses/antons_opengl_tutorials_book#16]
Hi,

I'm running Arch, with dual Radeon R9 290X cards (although I dare say only one works), with the open-source driver. In order to get it to chose opengl 4 I had to employ the same workaround that you have listed for apple. Not strictly an "issue", but might be worth dropping into the comments around that bit of code.

Thx.

**Comment by capnramses** [comment]
added comment to `00_hello_triangle/main.c`
```
Remove the #ifdef #endif and play around with this - you should be starting
an explicit version anyway, and some non-Apple drivers will require this too.
```
