### ISSUE TITLE
Phong shading - Broken fragment shader

### ISSUE THREAD

**Issue by battila7** [capnramses/antons_opengl_tutorials_book#19]
Hello!

Erroneous file: [08_phong/test_fs.glsl](https://github.com/capnramses/antons_opengl_tutorials_book/blob/master/08_phong/test_fs.glsl)

While making our way through the material of this book in class, we've noticed that there is something off with the fragment shader of the Phong shading example.

When running the example program of the book with one triangle (and the same, unit-length normals for every vertex), the shading was correct. However it failed to produce a correct result for a sphere that  consists of triangles with different per vertex normals.

After we've made sure that our normal calculations are correct, we've turned to the fragment shader. Basically we've compared it to the Phong shading code published in the [OpenGL 4.0 Shading Language Cookbook written by David Wolff](https://www.packtpub.com/game-development/opengl-40-shading-language-cookbook) (First Edition, pages 89-90).
The erroneous shading is caused by the non-unit normal vector lengths. The length of the `normal_eye` variable is *not* guaranteed to be `1.0` because it is an interpolated value calculated from the vertex normals on a per-fragment basis. So it must be normalized before using it in the `dot` and `reflect` calls in [line 30](https://github.com/capnramses/antons_opengl_tutorials_book/blob/master/08_phong/test_fs.glsl#L30) and [line 37](https://github.com/capnramses/antons_opengl_tutorials_book/blob/master/08_phong/test_fs.glsl#L37). The [documentation](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/reflect.xhtml) of the `reflect` function explicitly states that 

> N should be normalized in order to achieve the desired result.

<div align="center">
<div>Original shader</div>
<img src="https://cloud.githubusercontent.com/assets/11032092/25538469/1e2b6f58-2c43-11e7-871f-86d84afcc5d9.png" width="300" height="200">
</div>

<div align="center">
<div>Fixed shader</div>
<img src="https://cloud.githubusercontent.com/assets/11032092/25538507/4bcf7c9c-2c43-11e7-96ba-7cf42f7c33be.png" width="300" height="200">
</div>

**Comment by capnramses** [comment]
thanks for the great description and bug catch!
feel free to PR against bugs
fixed shaders in a couple of demos. there may be some more i didn't catch.
