### ISSUE TITLE
Uncomfortable camera movement

### ISSUE THREAD

**Issue by battila7** [capnramses/antons_opengl_tutorials_book#20]
Hello again! :smile:

Erroneous file: [05_virtual_camera/main.cpp](https://github.com/capnramses/antons_opengl_tutorials_book/blob/master/05_virtual_camera/main.cpp)

Working with the camera explained in the book is rather uncomfortable. Specifically, I'm talking about the way it can be moved around the scene. In most of the graphical softwares and games the user can move forward in the direction the camera's facing. Other movement directions (called by pressing A, S and D respectively) are also relative to the actual direction of the eye. However in the book these movement directions are constant, the direction where we look does not influence them.
In my opinion, a camera that moves with respect to where it looks is much more comfortable to use and does not introduce unbearable complexity.

Also, I'd like to point out that redeclaring the `T`, `R` and `view_mat` variables is a very bad practice and makes the code harder to understand and modify (talking about [lines 133-136](https://github.com/capnramses/antons_opengl_tutorials_book/blob/master/05_virtual_camera/main.cpp#L133-L136) and [lines 209-212](https://github.com/capnramses/antons_opengl_tutorials_book/blob/master/05_virtual_camera/main.cpp#L209-L212)).

If you like this addition, then I can make a pull request with the modified camera movement code. It's actually pretty simple, but rather long (the length of the rendering loop) so I'd not post it here, just explain how it works. 
First it extracts the direction where we look at from the `view_mat`. Then depending on the button pressed, a vector based on this direction is calculated (perpendicular to the right, perpendicular to the left, or opposite direction in the case of `S`). In the last step this vector gets scaled by the `cam_speed` and the `elapsed_seconds` and is added to the `cam_pos` vector.

**Comment by RySpk** [comment]
Pleas make a pull request or if no one else is interested in the code pls post a link to the source code. I am currently trying to create a better camera movement but it is really difficult for me. I don't have that much experience with 3D maths yet so i would really appreciate any help. :)

**Comment by capnramses** [comment]
sorry just saw these issues now!
if you still have your code for camera impl online we can link to it from the main Readme.md
