### ISSUE TITLE
use stbi flip function

### ISSUE THREAD

**Issue by postfixNotation** [capnramses/antons_opengl_tutorials_book#28]
https://github.com/capnramses/antons_opengl_tutorials_book/blob/be7bccca1d7f905736c55abb71065eaa25e0e85d/09_texture_mapping/main.cpp#L51-L61

a "stbi_set_flip_vertically_on_load(true);" before loading the image "stbi_load(...)" flips the image, so there's no need for these lines. I'm studying your OpenGL book purchased from Amazon, it's a great learning resource, thanks!

**Comment by capnramses** [comment]
want to make a PR? i'll merge it and put you on the contribs list
