### ISSUE TITLE
07_ray_picking example won't work correctly when framebuffer size is changed 

### ISSUE THREAD

**Issue by Gnimuc** [capnramses/antons_opengl_tutorials_book#30]
for example, when moving the window from an ordinary screen to a retina screen, the `get_ray_from_mouse` needs to scale mouse position according to the framebuffer size.

**Comment by capnramses** [comment]
good catch!

this code was written before retina or framebuffer v window dims existed.
there was an update to the demos to change window dimesnions `g_gl_width` etc to framebuffer dimensions with the glfw framebuffer callback.
the `get_ray_from_mouse` function still expects those variables to be the window size.

i think probably we need to keep track of both window dimensions and framebuffer dimensions, and name them clearly.
viewport etc use framebuffer dimensions.
mouse coordinate use window dimensions.

**Comment by capnramses** [comment]
feel free to fire a PR up - otherwise i will fix it when i get some time

**Comment by capnramses** [comment]
pushed a potential fix

* demo now works if you resize the window ( camera perspective and viewport update accordingly )
* window and framebuffer dimensions are treated separately ( should fix retina fb differing from window dims )

**Comment by capnramses** [comment]
just need to test on an osx retina device

**Comment by capnramses** [comment]
i think i can close this after comparing to other code i have that is retina tested, and reopen if someone with a retina device finds a problem

**Comment by Gnimuc** [comment]
thanks for the quick fix! I'll give it a test tonight.

**Comment by capnramses** [comment]
tested on a retina macbook. looks like it works when fb size differs from windows size.
had to modify the makefile to get it to build on a newer darwin o/s so pushed that too (removed some flags)
