### ISSUE TITLE
Unformatted code 

### ISSUE THREAD

**Issue by WorkShoft** [capnramses/antons_opengl_tutorials_book#38]
The main.cpp files appear to be unformatted, which makes some parts a bit hard to read. 

I suggest applying clang-format to these, I have been trying it locally and the results are very good. 

All that is needed is choosing a formatting style from llvm, google, chromium, mozilla, webkit, and microsoft. 

I have tested it with llvm and it turns code like this:

![Screenshot from 2020-07-05 12-53-15](https://user-images.githubusercontent.com/8629736/86531091-ac2e4a80-bebe-11ea-894b-473d511c0754.png)

into this:

`GLfloat proj_mat[]  = { Sx, 0.0f, 0.0f, 0.0f, 0.0f, Sy, 0.0f, 0.0f, 0.0f, 0.0f, Sz, -1.0f, 0.0f, 0.0f, Pz, 0.0f };`

**Comment by capnramses** [comment]
thanks WorkShoft! is that in 05_virtual_camera? looks like it encountered an auto-formatting accident that mangled it at some point...

**Comment by capnramses** [comment]
start a PR ( linked in the sidebar to this issue ) if you'd like to confirm that looks better. it's a long time since i checked out the .clang-format file in the repo so it might have messed things up convention-wise compared to the book text

**Comment by capnramses** [comment]
committed a mass clang-format -i to the main branch. thank you for the report.
