### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [capnramses/antons_opengl_tutorials_book#52]
I created Empty C++ project and installed all the libraries with NuGet. Am I supposed to copy-paste all the examples into my empty project now to run them?

**Comment by capnramses** [comment]
Hi! You can do that one-at-a-time, that's probably quickest.

In the case of building and running _all_ examples separately to try all the demos;

- It's possible to have multiple Projects in one Solution share NuGet dependencies but it's a bit of busy-work to set up.
- It's much quicker to use GCC from the command-line in this sort of case after downloading the libraries once.
- You can also use `cl` from the command-line to use Visual Studio's compiler but skip all the clicking, in the same way as you would use gcc.
